### ISSUE TITLE
image creation error

### ISSUE THREAD

**Issue by cKlee** [josd/eye#2]
Hi,

I'm trying to install EYE through ```install.sh``` and getting the error:

    --image eye.pvm
    eye --image eye.pvm
    ERROR: -g main: */2: Arithmetic: evaluation error: `int_overflow'

I have installed SWI-Prolog version 7.5.1

**Comment by josd** [comment]
Hi Carsten,

Thanks for the observation and the error message is indeed not very clear.
The latest EYE is now showing
** ERROR ** EYE requires swipl with the GMP library installed e.g sudo apt
install libgmp-dev

Hope that helps.


-- https://josd.github.io/ <http://josd.github.io/>

**Comment by cKlee** [comment]
Thanks!
