### ISSUE TITLE
swipl error.

### ISSUE THREAD

**Issue by Myeongjoon** [josd/eye#3]
I'm trying to install eye with my linux server.

but this error evoke.

```
kimmj8409@eyeserver:~/eye$ ./install.sh
/opt/eye/lib ~/eye
eye --image eye.pvm
** ERROR ** EYE requires swipl package clib which can be installed from http://www.swi-prolog.org/Download.html
~/eye
kimmj8409@eyeserver:~/eye$ swipl --version
SWI-Prolog version 7.4.1 for x86_64-linux
kimmj8409@eyeserver:~/eye$ 
```

this message say did not have swipl but can use swipl command.
Is there any hint?

**Comment by josd** [comment]
Hi,

This error message tells that swipl is installed but without package clib which is required for EYE.
What I normally do on Linux is:

git clone https://github.com/SWI-Prolog/swipl
cd swipl
./configure
# .. run git submodule update --init? yes
make
sudo make install
cd packages/clib
./configure
make
sudo make install

Kind regards,
Jos

**Comment by Myeongjoon** [comment]
thank you.
