### ISSUE TITLE
Could you please extend e:fail and e:findall to enable it to take a formula as the subject?

### ISSUE THREAD

**Issue by blackwint3r** [josd/eye#34]
Just as you have extended `e:call` [here](https://github.com/josd/eye/issues/31) to enable it to take a formula as the subject. 
I have to use `e:findall` and `e:fail` in the same way when implementing certain functions (for example, use `e:findall` to find a pattern in a formula).

Here is a simple test:
```
PREFIX e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>
PREFIX log: <http://www.w3.org/2000/10/swap/log#>
PREFIX : <#>

:g1 :content {
        {?x a :mortal} <= {?x a :human}.
        :Socrates a :human.
        }. 

{:g1!:content e:findall ( ?x {?x a :mortal} ?ANSWER ). ?ANSWER log:equalTo (:Socrates)} => {:TEST :PASS 1}.
{:g1!:content e:fail {:Socrates a :female}} => {:TEST :PASS 2}.
{:g1!:content e:call {:Socrates a :mortal}} => {:TEST :PASS 3}. 
```
Currently we got `:TEST :PASS 3` only ( With `--pass-only-new`).

Thanks in advance!

**Comment by josd** [comment]
I see your point and the latest version https://github.com/josd/eye/releases/tag/v22.0218.2226 should now give
```
:TEST :PASS 1 .
:TEST :PASS 2 .
:TEST :PASS 3 .
```
There was also a bug in `e:call` in that it always succeeded and that should be fixed as well.
Thanks for testing!
