### ISSUE TITLE
Is 'PREFIX' instead of '@prefix' a problem?

### ISSUE THREAD

**Issue by bencomp** [josd/eye#4]
The EYE server returns its results with prefix declarations as

    PREFIX : <http://www.agfa.com/w3c/euler/socrates#>

whereas the [N3 specification](https://www.w3.org/TeamSubmission/n3/) says they should be written

    @prefix : <http://www.agfa.com/w3c/euler/socrates#> .

The differences are the `@` to signal the keyword and the `.` to finish the declaration (and the capitalisation). However, it doesn't seem to bother a tool like the [OpenLink Data Sniffer](http://osds.openlinksw.com/) or EYE itself when providing N3 in this format. Is this a non-issue or are tools too accepting?

**Comment by josd** [comment]
Hi,

Right and this is due to RDF 1.1 Turtle [1]
and the fact that N3 is a superset of RDF.

Kind regards,
Jos

[1] https://www.w3.org/TR/turtle/


-- https://josd.github.io/ <http://josd.github.io/>

**Comment by bencomp** [comment]
Thanks, I see it now.
