### ISSUE TITLE
Issues with using the Prolog built-ins

### ISSUE THREAD

**Issue by nalhaidersogyo** [josd/eye#6]
Hi,

I was wondering what the status is of using the Prolog built-ins through the EYE reasoner. According to some of the tutorial slides they could be used using the prolog namespace. I could get the other namespaced built-ins (list, math, log, etc) to work, but those in the prolog namespace http://eulersharp.sourceforge.net/2003/03swap/prolog.html do not seem to be available. 

I have went through the source a bit and it says they are deprecated. I am new to the reasoner so I might have missed something. If it is still possible to use them are there any test cases that could show how?

**Comment by josd** [comment]
Hi,

Yes indeed, according to https://github.com/josd/eye/blob/master/RELEASE
[v17.0811.0745] deprecating prolog: built-ins and using e:calculate and e:derive instead

You can find some details about e:calculate and e:derive at https://github.com/josd/eye/blob/master/log-rules.n3

For more examples see for instance in https://github.com/josd/fluid/blob/master/fgcm/fgcm-plugin.n3

Kind regards,
Jos
