### ISSUE TITLE
Please tag releases in source, and avoid including zip with source

### ISSUE THREAD

**Issue by jonassmedegaard** [josd/eye#7]
It seems "releases" of this project are made by replacing eye.zip in source.

Please tag releases as git tags, to ease tracking releases.

Also, please consider not adding zip to source: Github offers automatically zip and tarballs of both tagged releases and each git commit, and adding zip to source causes the source to unnecessarily consume lots of space.

**Comment by jonassmedegaard** [comment]
If you want to drastically save space (i.e. download time for initial cloning), then _before_ tagging you might want to rewrite history to remove eye.zip from all commits (see first entry of the EXAMPLES section in `git help filter-branch`).
Normally it is bad to rewrite history, but arguably storing binary blobs in a source git is worse.  Just a suggestion.

While at it, you might want to strip reasoning/image/ype.pvm as well: I believe that contains code you did not write (I'll file a separate issue about the legal implications of that).

**Comment by josd** [comment]
There is now https://github.com/josd/eye/releases/tag/v18.1111.2230

The minimal eye.zip is still needed in other projects such as e.g. https://github.com/bdevloed/eye/blob/master/Dockerfile
